apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"

  name: inflate
  namespace: default
  resourceVersion: "52614"

spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: inflate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inflate
    spec:

      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        imagePullPolicy: IfNotPresent
        name: inflate
        resources:
          requests:
            cpu: "1"

        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      tolerations:

      - key: deployment
        operator: Equal
        value: cost-optimized-spot-pool
        effect: "NoSchedule"
