apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: elastic-stack
  annotations:
    # load balancer priority, lower numbers are evaluated first

    alb.ingress.kubernetes.io/group.order: "10"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # in seconds
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/healty-threshold-count: "1"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    external-dns.alpha.kubernetes.io/hostname: kibana.tools.devopsworks.io

  name: kibana
spec:
  # if you have the `ingressclass.kubernetes.io/is-default-class=true`
  # annotation on the ingress class, you don't need this
  ingressClassName: alb
  rules:
  - host: kibana.tools.devopsworks.io
    http:
      paths:
      - backend:
          service:
            name: ecs-stack-quickstart-eck-kibana-kb-http
            port:
              number: 5601
        path: /
        pathType: Prefix
